import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MouseCircle from "@/components/ui/MouseCircle";
import { AlertProvider } from "@/context/AlertContext";
import AuthProvider from "./providers/AuthProvider";
import Navbar from "@/components/ui/Navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <AlertProvider>
            <MouseCircle />
            <Navbar/>
            {children}
          </AlertProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
